<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon Condition="$([MSBuild]::IsOSPlatform('Windows'))">wwwroot\assets\icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="wwwroot\**" />
		<None Update="wwwroot\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>false</ExcludeFromSingleFile>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Photino.NET" Version="4.0.16" />
		<PackageReference Include="SharpHook" Version="7.1.3" />
	</ItemGroup>

</Project>
